name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Upload Sphinx docs to Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'elastica_model_pkg/docs/_build/html/'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2